function initThreeRace(){if(threeRace||!window.THREE)return false;const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xc4d6de,300,1000);const camera=new THREE.PerspectiveCamera(64,1,.08,1800),renderer=new THREE.WebGLRenderer({canvas:race3d,antialias:true,powerPreference:'high-performance',precision:'highp'});renderer.setPixelRatio(Math.min(2,devicePixelRatio||1));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;scene.add(new THREE.HemisphereLight(0xdcebff,0x3a4a26,1.3));const sun=new THREE.DirectionalLight(0xfff0d2,3.3);sun.position.set(-260,360,180);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-500;sun.shadow.camera.right=500;sun.shadow.camera.top=500;sun.shadow.camera.bottom=-500;sun.shadow.camera.far=1100;scene.add(sun);
 raceFX.ground(scene,renderer);
 const railMat=new THREE.MeshStandardMaterial({color:0xf7f5e8,roughness:.55}),goldMat=new THREE.MeshStandardMaterial({color:0xd2a23b,roughness:.55}),navyMat=new THREE.MeshStandardMaterial({color:0x102d4b,roughness:.65});function rail(offset){for(let i=0;i<160;i++){const a=trackPose(i/160,offset),b=trackPose((i+1)/160,offset),mid=a.p.clone().add(b.p).multiplyScalar(.5),len=a.p.distanceTo(b.p);const bar=new THREE.Mesh(new THREE.BoxGeometry(.38,.34,len+.25),railMat);bar.position.set(mid.x,1.15,mid.z);bar.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),b.p.clone().sub(a.p).normalize());scene.add(bar);if(i%4===0){const post=new THREE.Mesh(new THREE.BoxGeometry(.48,1.5,.48),railMat);post.position.copy(a.p);post.position.y=.7;scene.add(post)}}}rail(-20);rail(20);
 const markers=[];for(let m=100;m<1600;m+=100){const t=RACE_ORIGIN+m/1600,p=trackPose(t,-22),s=new THREE.Sprite(new THREE.SpriteMaterial({map:makeLabel(String(1600-m)),transparent:true}));markers.push([m/1600,s]);s.position.copy(p.p);s.position.y=4.15;s.scale.set(8.8,3.8,1);scene.add(s);const pole=new THREE.Mesh(new THREE.BoxGeometry(.3,4.2,.3),railMat);pole.position.copy(p.p);pole.position.y=2;scene.add(pole)}
 createRoyalFinishArch(scene);
 const bollardMat=new THREE.MeshStandardMaterial({color:0xf2ead8,roughness:.72});for(let i=0;i<48;i++){const p=trackPose(i/48,33),post=new THREE.Mesh(new THREE.CylinderGeometry(.15,.18,.72,8),bollardMat);post.position.copy(p.p);post.position.y=.34;scene.add(post)}
 const podium=createPodium(scene);enhancePodium(podium);const stalls=createStartingStalls(scene),loader=new THREE.TextureLoader(),horses=[],horseTextures=[],podiumTextures=[],silks=[];for(let i=0;i<6;i++){const configure=loaded=>{loaded.anisotropy=renderer.capabilities.getMaxAnisotropy();loaded.minFilter=THREE.LinearMipmapLinearFilter;loaded.magFilter=THREE.LinearFilter;loaded.needsUpdate=true},raceTex=new THREE.Texture(),frontTex=new THREE.Texture();const mat=new THREE.SpriteMaterial({map:raceTex,transparent:true,alphaTest:.025,color:0xffffff,depthWrite:false}),sprite=new THREE.Sprite(mat);sprite.scale.set(i?7.2:7.9,i?10.2:11.2,1);sprite.frustumCulled=false;scene.add(sprite);horses.push(sprite);horseTextures.push(raceTex);podiumTextures.push(frontTex);const kit=new THREE.Object3D();kit.visible=false;scene.add(kit);silks.push(kit)}threeRace={scene,camera,renderer,horses,horseTextures,podiumTextures,silks,podium,stalls,startPhase:'idle',introStart:0,goTime:0,falseStartPenalty:0,podiumActive:false,podiumOrder:[],lastW:0,lastH:0,camPos:null,camTarget:null,markers};raceFX.build(threeRace);$('#raceScreen').classList.add('webgl-active');return true}
function renderPodiumScene(q,now){const slots=[{x:0,h:3.3},{x:-6,h:2.2},{x:6,h:1.5}];q.podium.visible=true;for(let i=0;i<q.horses.length;i++){const slotIndex=q.podiumOrder.indexOf(i),visible=slotIndex>=0;q.horses[i].visible=visible;q.silks[i].visible=false;if(visible){const slot=slots[slotIndex],bounce=Math.sin(now*.003+i)*.025;q.horses[i].material.map=q.podiumTextures[i];raceFX.podium(q,i);q.horses[i].position.set(slot.x,slot.h+4.3+bounce,0);q.horses[i].scale.set(4.3,8.6,1)}}const desired=new THREE.Vector3(0,11.5,29),target=new THREE.Vector3(0,5,0);if(!q.camPos){q.camPos=desired.clone();q.camTarget=target.clone()}q.camPos.lerp(desired,.045);q.camTarget.lerp(target,.055);q.camera.position.copy(q.camPos);q.camera.lookAt(q.camTarget);q.podium.rotation.y=Math.sin(now*.00035)*.025;raceFX.render(q);return true}
function renderThreeRace(now,w,h){const q=threeRace;if(!q||w<2||h<2)return false;if(w!==q.lastW||h!==q.lastH){q.lastW=w;q.lastH=h;q.renderer.setSize(w,h,false);q.camera.aspect=w/h;q.camera.updateProjectionMatrix()}if(q.podiumActive)return renderPodiumScene(q,now);const source=visualProgress.length?visualProgress:progress;for(let i=0;i<q.horses.length;i++){const lane=i===0?(playerLane-50)*.38:(rivalLanes[i-1]-50)*.38,p=trackPose(RACE_ORIGIN+(source[i]||0)/100-(q.startPhase==='running'?0:.003),lane),speed=i?(rivalAI[i-1]?.speed||rivalBase[i-1]):autoSpeed,stride=now*(.0165+speed*.004)+i*1.7,beat=Math.sin(stride*Math.PI*.5),lift=Math.abs(Math.sin(stride*Math.PI));raceFX.horse(q,i,p,speed,now)}if(q.startPhase!=='running')return renderRaceIntro(q,now);if(q.stalls.visible&&source[0]>1.8)q.stalls.visible=false;if(q.finishView){const finish=trackPose(RACE_ORIGIN,0),desired=finish.p.clone().addScaledVector(finish.n,58);desired.y=13;const aim=finish.p.clone().addScaledVector(finish.f,-3);aim.y=4;if(!q.camPos){q.camPos=desired.clone();q.camTarget=aim.clone()}q.camPos.lerp(desired,.09);q.camTarget.lerp(aim,.1);q.camera.position.copy(q.camPos);q.camera.lookAt(q.camTarget);raceFX.render(q);return true}
 const player=trackPose(RACE_ORIGIN+(source[0]||0)/100,(playerLane-50)*.38),side=lookDir*8,desired=player.p.clone().addScaledVector(player.f,-26).addScaledVector(player.n,side);desired.y=10.5;const aim=player.p.clone().addScaledVector(player.f,62).addScaledVector(player.n,side*.65);aim.y=3.6;if(!q.camPos){q.camPos=desired.clone();q.camTarget=aim.clone()}{const k=Math.min(60,(now-(q.lastCam||now))/16.7);q.lastCam=now;q.camPos.lerp(desired,1-Math.pow(.85,k));q.camTarget.lerp(aim,1-Math.pow(.83,k))}q.camera.position.copy(q.camPos);q.camera.lookAt(q.camTarget);raceFX.render(q);return true}
function renderScene(now=0){if(!$('#raceScreen').classList.contains('open'))return;const world=$('#povWorld'),w=world.clientWidth,h=world.clientHeight,dt=Math.min(34,now-lastScene||16.67);lastScene=now;if(!visualProgress.length)visualProgress=progress.slice();for(let i=0;i<progress.length;i++)visualProgress[i]+=(progress[i]-visualProgress[i])*Math.min(1,dt*.018);if(threeRace)renderThreeRace(now,w,h);sceneFrame=requestAnimationFrame(renderScene)}
function courseTurn(p){const bell=(a,b,x)=>{if(x<=a||x>=b)return 0;return Math.sin((x-a)/(b-a)*Math.PI)};return bell(.015,.265,p)+bell(.515,.765,p)}
function startRace(){if(!window.THREE)return toast('Le moteur 3D n’a pas pu se charger. Recharge la page.');const RH=stable.active();if(RH.injury)return toast(`${RH.name} est blessé`);if(RH.fatigue>=90)return toast(`${RH.name} est trop fatigué pour courir`);if(!currentField)buildField();if(state.feed<RACE.fee)return toast('Fourrage insuffisant');racePlayer=terrainPerf(stable.racePerf(RH.stats,RH,RACE.dist,RH.dist,state.strategy),RH.stats);$('#goBtn').hidden=true;state.feed-=RACE.fee;sync();raceSeed=currentField.seed;raceRng=seeded(raceSeed);raceHeader();$('#panel').classList.remove('open');$('#raceScreen').classList.add('open');initThreeRace();if(threeRace){applyRaceQuality(threeRace);raceFX.liveries(threeRace);threeRace.markers.forEach(([f,s])=>{s.material.map?.dispose();s.material.map=makeLabel(String(Math.round(RACE.dist*(1-f)/100)*100));s.material.needsUpdate=true})}sound.music(false);sound.crowdStart();sound.crowdLevel(.1);playerLane=44;[12,28,56,72,88].forEach((v,i)=>rivalLanes[i]=v);if(threeRace){threeRace.camPos=null;threeRace.camTarget=null;threeRace.finishView=false;threeRace.podiumActive=false;threeRace.podium.visible=false;threeRace.stalls.visible=true;threeRace.stalls.userData.doors.forEach(d=>{d.rotation.x=0;d.position.set(0,0,3.58)});threeRace.startPhase='cinematic';threeRace.introStart=performance.now();threeRace.goTime=0;threeRace.falseStartPenalty=0;threeRace.horses.forEach((h,i)=>{h.visible=true;h.material.map=threeRace.horseTextures[i];h.material.needsUpdate=true});threeRace.silks.forEach(s=>s.visible=false)}$('#raceResult').classList.remove('show');$('#finishBoard').classList.remove('show');$('#startSequence').classList.remove('waiting');progress=[0,0,0,0,0,0];visualProgress=progress.slice();raceFinished=Array(6).fill(false);raceFinishTimes=Array(6).fill(0);finishOrder=[];rivalAI=[];raceTime=0;raceStartClock=0;autoSpeed=.42;sprintUntil=0;startBoostUntil=0;sprintReady=true;playerEnergy=100;updateEnergy();$('#sprintBtn').disabled=true;$('#sprintBtn').classList.remove('active');lookDir=0;updateLane();cancelAnimationFrame(sceneFrame);lastScene=0;sceneFrame=requestAnimationFrame(renderScene);$('#raceComment').textContent='Présentation de l’hippodrome…';clearInterval(raceLoop);raceLoop=null}
function clampRace(value,min,max){return Math.max(min,Math.min(max,value))}
function updateEnergy(){const amount=Math.round(playerEnergy);$('#energyValue').textContent=amount+' %';$('#energyFill').style.width=amount+'%';$('#energyFill').style.filter=amount<25?'hue-rotate(-40deg) saturate(1.8)':''}
function nearbyHorses(index){const own=progress[index],lane=index? rivalLanes[index-1]:playerLane;return progress.map((p,j)=>({p,j,l:j?rivalLanes[j-1]:playerLane,gap:p-own})).filter(x=>x.j!==index&&!raceFinished[x.j]&&x.gap>0&&x.gap<5).sort((a,b)=>a.gap-b.gap)}
function drafting(index){const lane=index?rivalLanes[index-1]:playerLane;return nearbyHorses(index).find(h=>h.gap>.5&&Math.abs(h.l-lane)<12)}
function initRivalAI(){const F=currentField||buildField();rivalAI=F.rivals.map((r,i)=>{const P=terrainPerf(stable.racePerf(r.stats,{form:52+raceRng()*18,fatigue:10,moral:65},RACE.dist,r.pref,['leader','stalker','finisher'][Math.floor(raceRng()*3)]),r.stats);return{P,speed:P.cruise,cruise:P.cruise,targetLane:[12,28,56,72,88][i],nextDecision:6+Math.floor(raceRng()*13),sprintAt:60+raceRng()*24,sprintUntil:0,sprints:0,energy:100,temper:1}})}
function markFinish(index){if(raceFinished[index]||progress[index]<100)return;raceFinished[index]=true;raceFinishTimes[index]=(raceTime-(progress[index]-100)/Math.max(.05,(index?rivalAI[index-1].speed:autoSpeed)*raceScaleNow()))*.2;finishOrder.push(index);progress[index]=101.35+finishOrder.length*.08;if(index===0){if(threeRace){threeRace.finishView=true;threeRace.camPos=null;threeRace.camTarget=null}$('#sprintBtn').disabled=true;$('#draft').classList.remove('show');$('#raceComment').textContent='Poteau franchi — caméra arrivée jusqu’au dernier cheval';$('#autoGallop b').textContent='Course terminée'}}
function runRaceV2(){raceTime++;const phase=progress[0],turn=courseTurn(Math.min(1,phase/100)),raceScale=raceScaleNow();sound.crowdLevel(Math.max(0,(Math.max(...progress)-60)/40));if(phase>75&&!raceFinished[0]&&!runRaceV2.said){runRaceV2.said=1;sound.say('Dernière ligne droite !');coach.tip('sprint','Dernière ligne droite : c’est le moment de lancer ton <b>SPRINT</b> si ton endurance le permet.','#sprintBtn')}if(phase>20&&phase<40&&!runRaceV2.tipd){runRaceV2.tipd=1;coach.tip('draft','Place-toi juste derrière un adversaire (◀ ▶) : dans son <b>sillage</b>, ton cheval dépense deux fois moins d’énergie.','.steer')}
 if(!raceFinished[0]){playerLane=clampRace(playerLane+turn*.12,7,93);updateLane();const ahead=nearbyHorses(0)[0],boxed=!!ahead&&ahead.gap<1.4&&Math.abs(ahead.l-playerLane)<11,inDraft=!!drafting(0),sprinting=raceTime<sprintUntil&&playerEnergy>2,wide=turn*Math.max(0,playerLane-18)/75;
 playerEnergy=clampRace(playerEnergy-(sprinting?racePlayer.sprintDrain*(inDraft?.7:1):racePlayer.drain*(inDraft?.5:1)*(phase<55?racePlayer.tactic.d:1))-wide*.03,0,100);updateEnergy();const cr=racePlayer.cruise*(phase<55?racePlayer.tactic.c:1),target=(boxed?racePlayer.boxed:sprinting?cr+racePlayer.sprint:phase>72?cr+.045:cr)*(1-wide*.105)*(playerEnergy<15?.85:playerEnergy<30?.95:1)+(inDraft?racePlayer.draft:0)+(raceRng()-.5)*racePlayer.noise*6;autoSpeed+=(target-autoSpeed)*.13;progress[0]+=autoSpeed*raceScale;
 $('#draft').classList.toggle('show',inDraft);$('#autoGallop').classList.toggle('blocked',boxed);$('#autoGallop b').textContent=boxed?'Foulée coupée':sprinting?'Sprint lancé':inDraft?'À l’abri du vent':playerEnergy<20?'Endurance faible':'Foulée libre';if(boxed)$('#raceComment').textContent='Bloqué : décale-toi pour relancer';else if(inDraft)$('#raceComment').textContent='Dans le sillage : tu économises ton endurance';else if(sprinting)$('#raceComment').textContent=HN()+' accélère !';else if(turn>.35&&playerLane>35)$('#raceComment').textContent='Rapproche-toi de la corde';else if(phase>76)$('#raceComment').textContent='Dernière ligne droite : prépare ton sprint !';if(!sprinting)$('#sprintBtn').classList.remove('active')}
 for(let i=0;i<5;i++){const idx=i+1,ai=rivalAI[i];if(raceFinished[idx])continue;const own=progress[idx],lane=rivalLanes[i],near=nearbyHorses(idx),ahead=near.find(h=>Math.abs(h.l-lane)<12),ropeBusy=progress.some((p,j)=>j!==idx&&!raceFinished[j]&&Math.abs(p-own)<2.5&&(j? rivalLanes[j-1]:playerLane)<24);
 if(raceTime>=ai.nextDecision){const gap=Math.max(...progress.filter((p,j)=>!raceFinished[j]))-own;const wantsAttack=own>ai.sprintAt||gap>6&&own>35&&raceRng()<.15;if(wantsAttack&&ai.energy>19&&raceTime>=ai.sprintUntil){ai.sprintUntil=raceTime+18+Math.floor(raceRng()*14);ai.sprints++;ai.sprintAt=own+13+raceRng()*20}
 if(ahead&&ahead.gap<1.3&&ai.energy>23&&raceRng()<.68)ai.targetLane=clampRace(lane+(lane<70?17:-17),9,80);else if(ahead&&ahead.gap<4&&ai.energy<64)ai.targetLane=clampRace(ahead.l+raceRng()*5-2.5,9,80);else ai.targetLane=ropeBusy?28+raceRng()*9:10+raceRng()*9;ai.nextDecision=raceTime+10+Math.floor(raceRng()*20)}
 if(ahead&&ahead.gap<.85&&Math.abs(ai.targetLane-lane)<11)ai.targetLane=clampRace(lane+(lane<70?17:-17),9,85);const step=clampRace((ai.targetLane-lane)*.12,-.85,.85);rivalLanes[i]=clampRace(lane+step,8,90);const shelter=!!drafting(idx),attacking=raceTime<ai.sprintUntil&&ai.energy>4,curve=courseTurn(Math.min(1,own/100)),wide=curve*Math.max(0,rivalLanes[i]-19)/75;
 const P=ai.P,early=own<55;ai.energy=clampRace(ai.energy-(attacking?P.sprintDrain*(shelter?.7:1):P.drain*(shelter?.5:1)*(early?P.tactic.d:1))-wide*.03,0,100);const target=(P.cruise*(early?P.tactic.c:1)+(attacking?P.sprint*clampRace(ai.energy/30,.55,1):0)+(own>72?.045:0)+(shelter?P.draft:0))*(1-wide*.125)*(ai.energy<15?.85:ai.energy<30?.95:1)+(raceRng()-.5)*P.noise*6;ai.speed+=(target-ai.speed)*.16;progress[idx]+=ai.speed*raceScale}
 for(let i=0;i<6;i++)markFinish(i);const ranked=progress.map((p,i)=>({p,i})).sort((a,b)=>b.p-a.p),rank=raceFinished[0]?finishOrder.indexOf(0)+1:ranked.findIndex(x=>x.i===0)+1;$('#racePosition').textContent=rank+(rank===1?'er':'e');$('#meters').textContent=fmt(Math.max(0,Math.round(RACE.dist*(1-Math.min(100,progress[0])/100))));$('#mapDot').style.left=Math.min(100,progress[0])+'%';if(finishOrder.length===6)completeRace()}
function completeRace(){clearInterval(raceLoop);raceLoop=null;const rank=finishOrder.indexOf(0)+1,win=rank===1;const prize=Math.round(RACE.purse*[1,.46,.26,.17,.13,.1][rank-1]);state.gold+=prize;sync();const AR=stable.afterRace(stable.data.active,rank,6),CR=career.afterRace(rank,RACE);sound.crowdLevel(1);setTimeout(()=>sound.crowdLevel(.2),2500);if(win){sound.fanfare();buzz([60,40,120])}else buzz(40);sound.say(`${raceNames[finishOrder[0]]} remporte le ${RACE.n} !`,true);$('#fbGain').textContent=`+${fmt(prize)} or · ${CR.d>0?'+':''}${CR.d} trophées · +${AR.xp} XP · Fatigue +24${AR.up?` · NIVEAU ${stable.active().level} !`:''}${CR.promoted?` · PROMU EN LIGUE ${CR.promoted.n.toUpperCase()} !`:CR.relegated?` · Retour en ligue ${CR.relegated.n}`:''}`;currentField=null;const first=raceFinishTimes[finishOrder[0]];$('#finishRows').innerHTML=finishOrder.map((idx,pos)=>{const gap=raceFinishTimes[idx]-first;return `<tr class="${idx===0?'player':''}"><td>${pos+1}</td><td>${escapeHTML(raceNames[idx])}${idx===0?' • VOUS':''}</td><td>${raceFinishTimes[idx].toFixed(2)} s</td><td>${pos?`+${gap.toFixed(2)} s`:'—'}</td></tr>`}).join('');$('#raceComment').textContent='Classement officiel validé';$('#finishBoard').classList.add('show');$('#resultCup').textContent=win?'🏆':'🎖️';$('#resultTitle').textContent=win?'Victoire royale !':`${rank}e place`;$('#resultText').textContent=win?HN()+' monte sur la première marche du podium.':`${HN()} termine ${rank}e après une course disputée.`}
function sprint(){if(!sprintReady||!raceLoop||raceFinished[0]||playerEnergy<8)return;sprintReady=false;sprintUntil=raceTime+32;career.bump('sprint');buzz(25);$('#sprintBtn').classList.add('active');$('#sprintBtn').disabled=true;$('#raceComment').textContent='Sprint lancé — trouve une ligne libre !';setTimeout(()=>{if($('#raceScreen').classList.contains('open')&&!raceFinished[0]){$('#sprintBtn').disabled=false;sprintReady=true}},8500)}
function updateLane(){playerLane=Math.max(7,Math.min(93,playerLane));$('#laneDot').style.left=playerLane+'%'}
function steer(dir){playerLane+=dir*10;updateLane();$('#raceComment').textContent=dir<0?'Tu te rapproches de la corde':'Tu prends l’extérieur'}
function look(dir){lookDir=dir;$('#lookLabel').textContent=dir<0?'Regard à gauche':'Regard à droite';$('#lookLabel').classList.add('show');$('#lookLeft').classList.toggle('active',dir<0);$('#lookRight').classList.toggle('active',dir>0);setTimeout(()=>{lookDir=0;$('#lookLeft').classList.remove('active');$('#lookRight').classList.remove('active');$('#lookLabel').classList.remove('show')},800)}
function leaveRace(){sound.crowdStop();sound.music(true);runRaceV2.said=0;runRaceV2.tipd=0;$('#goBtn').hidden=true;clearInterval(raceLoop);raceLoop=null;cancelAnimationFrame(sceneFrame);$('#raceScreen').classList.remove('open');$('#raceResult').classList.remove('show');$('#finishBoard').classList.remove('show');$('#startSequence').classList.remove('show','waiting');if(threeRace){threeRace.startPhase='idle';threeRace.finishView=false;threeRace.podiumActive=false}}
function showPodium(){if(finishOrder.length<3)return;$('#finishBoard').classList.remove('show');if(threeRace){threeRace.finishView=false;threeRace.camPos=null;threeRace.camTarget=null;threeRace.podiumOrder=finishOrder.slice(0,3);threeRace.podiumActive=true;}$('#raceComment').textContent='Cérémonie du Podium Royal';setTimeout(()=>{if($('#raceScreen').classList.contains('open'))$('#raceResult').classList.add('show')},2400)}
function raceScaleNow(){return .44*1600/RACE.dist}
function terrainPerf(P,st){const T=TERRAINS[RACE.terrain]||TERRAINS.bon,k=T.drain>1?(1.25-st.end*.005):1;const L=Math.pow(1600/RACE.dist,.55);return{...P,cruise:P.cruise*T.speed,drain:P.drain*(1+(T.drain-1)*k*1.6)*L,sprintDrain:P.sprintDrain*T.drain}}
function raceHeader(){$('.race-head h2').textContent=RACE.n;$('.race-head small').textContent=`Hippodrome Royal • ${fmt(RACE.dist)} m • Terrain ${TERRAINS[RACE.terrain].n.toLowerCase()} • 6 partants`;$('#meters').textContent=fmt(RACE.dist)}
