function initThreeRace(){if(threeRace||!window.THREE)return false;const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xc4d6de,300,1000);const camera=new THREE.PerspectiveCamera(64,1,.08,1800),renderer=new THREE.WebGLRenderer({canvas:race3d,antialias:true,powerPreference:'high-performance',precision:'highp'});renderer.setPixelRatio(Math.min(2,devicePixelRatio||1));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;const hemi=new THREE.HemisphereLight(0xdcebff,0x3a4a26,1.3);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff0d2,3.3);sun.position.set(-260,360,180);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-500;sun.shadow.camera.right=500;sun.shadow.camera.top=500;sun.shadow.camera.bottom=-500;sun.shadow.camera.far=1100;scene.add(sun);
 raceFX.ground(scene,renderer);
 const railMat=new THREE.MeshStandardMaterial({color:0xf7f5e8,roughness:.55}),goldMat=new THREE.MeshStandardMaterial({color:0xd2a23b,roughness:.55}),navyMat=new THREE.MeshStandardMaterial({color:0x102d4b,roughness:.65});function rail(offset){for(let i=0;i<160;i++){const a=trackPose(i/160,offset),b=trackPose((i+1)/160,offset),mid=a.p.clone().add(b.p).multiplyScalar(.5),len=a.p.distanceTo(b.p);const bar=new THREE.Mesh(new THREE.BoxGeometry(.38,.34,len+.25),railMat);bar.position.set(mid.x,1.15,mid.z);bar.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),b.p.clone().sub(a.p).normalize());scene.add(bar);if(i%4===0){const post=new THREE.Mesh(new THREE.BoxGeometry(.48,1.5,.48),railMat);post.position.copy(a.p);post.position.y=.7;scene.add(post)}}}rail(-20);rail(20);
 const markers=[];for(let m=100;m<1600;m+=100){const t=RACE_ORIGIN+m/1600,p=trackPose(t,-22),s=new THREE.Sprite(new THREE.SpriteMaterial({map:makeLabel(String(1600-m)),transparent:true}));markers.push([m/1600,s]);s.position.copy(p.p);s.position.y=4.15;s.scale.set(8.8,3.8,1);scene.add(s);const pole=new THREE.Mesh(new THREE.BoxGeometry(.3,4.2,.3),railMat);pole.position.copy(p.p);pole.position.y=2;scene.add(pole)}
 createRoyalFinishArch(scene);
 const bollardMat=new THREE.MeshStandardMaterial({color:0xf2ead8,roughness:.72});for(let i=0;i<48;i++){const p=trackPose(i/48,33),post=new THREE.Mesh(new THREE.CylinderGeometry(.15,.18,.72,8),bollardMat);post.position.copy(p.p);post.position.y=.34;scene.add(post)}
 const podium=createPodium(scene);enhancePodium(podium);const stalls=createStartingStalls(scene),loader=new THREE.TextureLoader(),horses=[],horseTextures=[],podiumTextures=[],silks=[];for(let i=0;i<6;i++){const configure=loaded=>{loaded.anisotropy=renderer.capabilities.getMaxAnisotropy();loaded.minFilter=THREE.LinearMipmapLinearFilter;loaded.magFilter=THREE.LinearFilter;loaded.needsUpdate=true},raceTex=new THREE.Texture(),frontTex=new THREE.Texture();const mat=new THREE.SpriteMaterial({map:raceTex,transparent:true,alphaTest:.025,color:0xffffff,depthWrite:false}),sprite=new THREE.Sprite(mat);sprite.scale.set(i?7.2:7.9,i?10.2:11.2,1);sprite.frustumCulled=false;scene.add(sprite);horses.push(sprite);horseTextures.push(raceTex);podiumTextures.push(frontTex);const kit=new THREE.Object3D();kit.visible=false;scene.add(kit);silks.push(kit)}threeRace={sun,hemi,scene,camera,renderer,horses,horseTextures,podiumTextures,silks,podium,stalls,startPhase:'idle',introStart:0,goTime:0,falseStartPenalty:0,podiumActive:false,podiumOrder:[],lastW:0,lastH:0,camPos:null,camTarget:null,markers};raceFX.build(threeRace);$('#raceScreen').classList.add('webgl-active');return true}
function renderPodiumScene(q,now){const slots=[{x:0,h:3.3},{x:-6,h:2.2},{x:6,h:1.5}];q.podium.visible=true;for(let i=0;i<q.horses.length;i++){const slotIndex=q.podiumOrder.indexOf(i),visible=slotIndex>=0;q.horses[i].visible=visible;q.silks[i].visible=false;if(visible){const slot=slots[slotIndex],bounce=Math.sin(now*.003+i)*.025;q.horses[i].material.map=q.podiumTextures[i];raceFX.podium(q,i);q.horses[i].position.set(slot.x,slot.h+4.3+bounce,0);q.horses[i].scale.set(4.3,8.6,1)}}const desired=new THREE.Vector3(0,11.5,29),target=new THREE.Vector3(0,5,0);if(!q.camPos){q.camPos=desired.clone();q.camTarget=target.clone()}q.camPos.lerp(desired,.045);q.camTarget.lerp(target,.055);q.camera.position.copy(q.camPos);q.camera.lookAt(q.camTarget);q.podium.rotation.y=Math.sin(now*.00035)*.025;raceFX.render(q);return true}
function renderThreeRace(now,w,h){const q=threeRace;if(!q||w<2||h<2)return false;if(w!==q.lastW||h!==q.lastH){q.lastW=w;q.lastH=h;q.renderer.setSize(w,h,false);q.camera.aspect=w/h;q.camera.updateProjectionMatrix()}if(q.podiumActive)return renderPodiumScene(q,now);const source=visualProgress.length?visualProgress:progress;for(let i=0;i<q.horses.length;i++){const lane=i===0?(playerLane-50)*.38:(rivalLanes[i-1]-50)*.38,p=trackPose(RACE_ORIGIN+(source[i]||0)/100-(q.startPhase==='running'?0:.003),lane),speed=i?(rivalAI[i-1]?.speed||rivalBase[i-1]):autoSpeed,stride=now*(.0165+speed*.004)+i*1.7,beat=Math.sin(stride*Math.PI*.5),lift=Math.abs(Math.sin(stride*Math.PI));raceFX.horse(q,i,p,speed,now)}if(q.startPhase!=='running')return renderRaceIntro(q,now);if(q.stalls.visible&&source[0]>1.8)q.stalls.visible=false;
 // caméra télé (replay) : au bord de la piste, elle suit le centre du peloton en travelling latéral
 if(q.tvView){const act=source.map(p=>Math.min(100.6,p||0)),mid=act.reduce((a,b)=>a+b,0)/act.length*.5+Math.max(...act)*.5,c=trackPose(RACE_ORIGIN+Math.min(100.4,mid)/100,0),desired=c.p.clone().addScaledVector(c.n,58).addScaledVector(c.f,-3);desired.y=15;const aim=c.p.clone().addScaledVector(c.f,-1);aim.y=2;
  if(!q.camPos){q.camPos=desired.clone();q.camTarget=aim.clone()}q.camPos.lerp(desired,.06);q.camTarget.lerp(aim,.09);q.camera.position.copy(q.camPos);q.camera.lookAt(q.camTarget);raceFX.render(q);return true}
 if(q.finishView){const finish=trackPose(RACE_ORIGIN,0),desired=finish.p.clone().addScaledVector(finish.n,58);desired.y=13;const aim=finish.p.clone().addScaledVector(finish.f,-3);aim.y=4;if(!q.camPos){q.camPos=desired.clone();q.camTarget=aim.clone()}q.camPos.lerp(desired,.09);q.camTarget.lerp(aim,.1);q.camera.position.copy(q.camPos);q.camera.lookAt(q.camTarget);raceFX.render(q);return true}
 const player=trackPose(RACE_ORIGIN+(source[0]||0)/100,(playerLane-50)*.38),side=lookDir*8,desired=player.p.clone().addScaledVector(player.f,-26).addScaledVector(player.n,side);desired.y=10.5;const aim=player.p.clone().addScaledVector(player.f,62).addScaledVector(player.n,side*.65);aim.y=3.6;if(!q.camPos){q.camPos=desired.clone();q.camTarget=aim.clone()}{const k=Math.min(60,(now-(q.lastCam||now))/16.7);q.lastCam=now;q.camPos.lerp(desired,1-Math.pow(.85,k));q.camTarget.lerp(aim,1-Math.pow(.83,k))}q.camera.position.copy(q.camPos);q.camera.lookAt(q.camTarget);raceFX.render(q);return true}
function renderScene(now=0){if(!$('#raceScreen').classList.contains('open'))return;const world=$('#povWorld'),w=world.clientWidth,h=world.clientHeight,dt=Math.min(34,now-lastScene||16.67);lastScene=now;if(!visualProgress.length)visualProgress=progress.slice();for(let i=0;i<progress.length;i++)visualProgress[i]+=(progress[i]-visualProgress[i])*Math.min(1,dt*.018);if(threeRace)renderThreeRace(now,w,h);sceneFrame=requestAnimationFrame(renderScene)}
function courseTurn(p){const bell=(a,b,x)=>{if(x<=a||x>=b)return 0;return Math.sin((x-a)/(b-a)*Math.PI)};return bell(.015,.265,p)+bell(.515,.765,p)}
function startRace(){if(!window.THREE)return toast('Le moteur 3D n’a pas pu se charger. Recharge la page.');const RH=stable.active();if(RH.injury)return toast(`${RH.name} est blessé`);if(RH.fatigue>=90)return toast(`${RH.name} est trop fatigué pour courir`);if(!currentField)buildField();if(state.feed<RACE.fee)return toast('Fourrage insuffisant');racePlayer=gear.apply(terrainPerf(stable.racePerf(RH.stats,RH,RACE.dist,RH.dist,state.strategy),RH.stats,RH.talent));playerFinal=false;resetRaceStats();$('#mapIdeal').style.opacity=1;$('#sprintBtn').dataset.st='';$('#sprintBtn').innerHTML='SPRINT<small>plus tard</small>';$('#sprintInfo').textContent='';$('#goBtn').hidden=true;state.feed-=RACE.fee;sync();raceSeed=currentField.seed;raceRng=seeded(raceSeed);raceHeader();$('#panel').classList.remove('open');$('#raceScreen').classList.add('open');initThreeRace();if(threeRace){applyRaceQuality(threeRace);raceFX.liveries(threeRace);threeRace.markers.forEach(([f,s])=>{s.material.map?.dispose();s.material.map=makeLabel(String(Math.round(RACE.dist*(1-f)/100)*100));s.material.needsUpdate=true})}sound.music(false);sound.crowdStart();sound.crowdLevel(.1);playerLane=44;[12,28,56,72,88].forEach((v,i)=>rivalLanes[i]=v);if(threeRace){threeRace.camPos=null;threeRace.camTarget=null;threeRace.finishView=false;threeRace.podiumActive=false;threeRace.podium.visible=false;threeRace.stalls.visible=true;threeRace.stalls.userData.doors.forEach(d=>{d.rotation.x=0;d.position.set(0,0,3.58)});threeRace.startPhase='cinematic';threeRace.introStart=performance.now();threeRace.lastIntro=0;threeRace.goTime=0;threeRace.falseStartPenalty=0;threeRace.horses.forEach((h,i)=>{h.visible=true;h.material.map=threeRace.horseTextures[i];h.material.needsUpdate=true});threeRace.silks.forEach(s=>s.visible=false)}$('#raceResult').classList.remove('show');$('#finishBoard').classList.remove('show');$('#startSequence').classList.remove('waiting');progress=[0,0,0,0,0,0];visualProgress=progress.slice();raceFinished=Array(6).fill(false);raceFinishTimes=Array(6).fill(0);finishOrder=[];rivalAI=[];raceTime=0;raceStartClock=0;autoSpeed=.42;startBoostUntil=0;playerEnergy=100;updateEnergy();$('#sprintBtn').disabled=true;$('#sprintBtn').classList.remove('active');lookDir=0;updateLane();cancelAnimationFrame(sceneFrame);lastScene=0;sceneFrame=requestAnimationFrame(renderScene);$('#raceComment').textContent='Présentation de l’hippodrome…';clearInterval(raceLoop);raceLoop=null;hooks.emit('race:start')}
function clampRace(value,min,max){return Math.max(min,Math.min(max,value))}
function updateEnergy(){const amount=Math.round(playerEnergy);$('#energyValue').textContent=amount+' %';$('#energyFill').style.width=amount+'%';$('#energyFill').style.filter=amount<25?'hue-rotate(-40deg) saturate(1.8)':''}
function nearbyHorses(index){const own=progress[index],lane=index? rivalLanes[index-1]:playerLane;return progress.map((p,j)=>({p,j,l:j?rivalLanes[j-1]:playerLane,gap:p-own})).filter(x=>x.j!==index&&!raceFinished[x.j]&&x.gap>0&&x.gap<5).sort((a,b)=>a.gap-b.gap)}
function drafting(index){const lane=index?rivalLanes[index-1]:playerLane;return nearbyHorses(index).find(h=>h.gap>.5&&Math.abs(h.l-lane)<12)}
function markFinish(index){if(raceFinished[index]||progress[index]<100)return;raceFinished[index]=true;raceFinishTimes[index]=(raceTime-(progress[index]-100)/Math.max(.05,(index?rivalAI[index-1].speed:autoSpeed)*raceScaleNow()))*.2;{const prev=finishOrder.length?raceFinishTimes[finishOrder[finishOrder.length-1]]:0;if(raceFinishTimes[index]<=prev)raceFinishTimes[index]=prev+.01}finishOrder.push(index);progress[index]=101.35+finishOrder.length*.08;if(index===0){RS.sprintLeft=playerFinal?playerEnergy:null;if(threeRace){threeRace.finishView=true;threeRace.camPos=null;threeRace.camTarget=null}$('#sprintBtn').disabled=true;$('#draft').classList.remove('show');$('#raceComment').textContent='Poteau franchi — caméra arrivée jusqu’au dernier cheval';$('#autoGallop b').textContent='Course terminée'}}
function updateLane(){playerLane=Math.max(7,Math.min(93,playerLane));$('#laneDot').style.left=playerLane+'%'}
function steer(dir){hooks.emit('race:steer',dir);playerLane+=dir*10;updateLane();$('#raceComment').textContent=dir<0?'Tu te rapproches de la corde':'Tu prends l’extérieur'}
function look(dir){lookDir=dir;$('#lookLabel').textContent=dir<0?'Regard à gauche':'Regard à droite';$('#lookLabel').classList.add('show');$('#lookLeft').classList.toggle('active',dir<0);$('#lookRight').classList.toggle('active',dir>0);setTimeout(()=>{lookDir=0;$('#lookLeft').classList.remove('active');$('#lookRight').classList.remove('active');$('#lookLabel').classList.remove('show')},800)}
function leaveRace(){hooks.emit('race:leave',finishOrder.length===6);sound.crowdStop();sound.music(true);runRaceV2.said=0;runRaceV2.tipd=0;$('#goBtn').hidden=true;clearInterval(raceLoop);raceLoop=null;cancelAnimationFrame(sceneFrame);$('#raceScreen').classList.remove('open');$('#raceResult').classList.remove('show');$('#finishBoard').classList.remove('show');$('#startSequence').classList.remove('show','waiting');if(threeRace){threeRace.startPhase='idle';threeRace.finishView=false;threeRace.podiumActive=false}}
function showPodium(){if(finishOrder.length<3)return;$('#finishBoard').classList.remove('show');if(threeRace){threeRace.finishView=false;threeRace.camPos=null;threeRace.camTarget=null;threeRace.podiumOrder=finishOrder.slice(0,3);threeRace.podiumActive=true;}$('#raceComment').textContent='Cérémonie du Podium Royal';setTimeout(()=>{if($('#raceScreen').classList.contains('open'))$('#raceResult').classList.add('show')},2400)}
function raceScaleNow(){return .44*1600/RACE.dist}
function terrainPerf(P,st,talent){const T=TERRAINS[RACE.terrain]||TERRAINS.bon,k=T.drain>1?(1.25-st.end*.005):1;const L=Math.pow(1600/RACE.dist,.55);const o={...P,talent,cruise:P.cruise*T.speed,drain:P.drain*(1+(T.drain-1)*k*1.6)*L,sprintDrain:P.sprintDrain*T.drain};if(talent==='finisseur')o.sprint*=1.15;if(talent==='increvable')o.drain*=RACE.terrain==='bon'?.95:.86;if(talent==='fusee')o.window+=60;if(talent==='tacticien'){o.draft*=1.5;o.boxed+=.02}if(talent==='metronome'){o.noise*=.3;o.drain*=.96}return o}
function raceHeader(){$('.race-head h2').textContent=RACE.n;$('.race-head small').textContent=`Hippodrome Royal • ${fmt(RACE.dist)} m • Terrain ${TERRAINS[RACE.terrain].n.toLowerCase()} • 6 partants`;$('#meters').textContent=fmt(RACE.dist);hooks.emit('race:header')}

function initRivalAI(){const F=currentField||buildField();rivalAI=F.rivals.map((r,i)=>{const tac=['leader','stalker','finisher'][Math.floor(raceRng()*3)],P=terrainPerf(stable.racePerf(r.stats,{form:52+raceRng()*18,fatigue:10,moral:65},RACE.dist,r.pref,tac),r.stats,r.talent);
 return{P,tac,speed:P.cruise,targetLane:[12,28,56,72,88][i],nextDecision:6+Math.floor(raceRng()*13),final:false,err:(raceRng()-.5)*.14+(tac==='leader'?-.06:tac==='finisher'?.04:0),energy:100}});hooks.emit('race:launch')}
/* portée du sprint final : combien de mètres le cheval peut sprinter avec l'énergie qui lui reste */
function sprintReach(P,energy,cruise){const perTick=(cruise+P.sprint)*raceScaleNow();return energy/Math.max(.01,P.sprintDrain)*perTick*RACE.dist/100}
function remainingM(p){return Math.max(0,RACE.dist*(100-p)/100)}
const RS={};function resetRaceStats(){Object.assign(RS,{ticks:0,draft:0,rail:0,boxed:0,reaction:0,window:180,sprintAtM:null,idealAtM:null,sprintLeft:null,exhaustedM:0,hadSprint:false})}
function runRaceV2(){if(coach.open)return;raceTime++;moments.tick();const phase=progress[0],turn=courseTurn(Math.min(1,phase/100)),raceScale=raceScaleNow();sound.crowdLevel(Math.max(0,(Math.max(...progress)-60)/40));
 if(phase>20&&phase<40&&!runRaceV2.tipd){runRaceV2.tipd=1;coach.tip('draft','Place-toi juste derrière un adversaire (◀ ▶) : dans son <b>sillage</b>, ton cheval dépense deux fois moins d’énergie.','.steer')}
 if(!raceFinished[0]){playerLane=clampRace(playerLane+turn*.12,7,93);updateLane();const P=racePlayer,ahead=nearbyHorses(0)[0],boxed=!!ahead&&ahead.gap<1.4&&Math.abs(ahead.l-playerLane)<11,inDraft=!!drafting(0),wide=turn*Math.max(0,playerLane-18)/75,sprinting=playerFinal&&playerEnergy>0,MF=moments.fx(0);
  const cr=P.cruise*(phase<55?P.tactic.c:1)*(P.talent==='fusee'&&phase<15?1.02:1)*(P.talent==='coeur'&&phase>75&&progress.some((p,j)=>j&&p>phase)?1.03:1);
  playerEnergy=clampRace(playerEnergy-(sprinting?P.sprintDrain*(inDraft?.8:1):P.drain*(inDraft?.5:1)*(phase<55?P.tactic.d:1)*MF.drain)-wide*.03,0,100);updateEnergy();
  const tired=playerEnergy<=0?.84:playerEnergy<15?.9:playerEnergy<30?.96:1,target=(boxed?P.boxed:sprinting?cr+P.sprint:phase>72?cr+.045:cr)*(1-wide*.105)*tired+(inDraft?P.draft:0)+MF.speed+(raceRng()-.5)*P.noise*6;autoSpeed+=(target-autoSpeed)*.13;progress[0]+=autoSpeed*raceScale;
  RS.ticks++;if(inDraft)RS.draft++;if(playerLane<24)RS.rail++;if(boxed)RS.boxed++;if(playerFinal&&playerEnergy<=0)RS.exhaustedM+=autoSpeed*raceScale*RACE.dist/100;
  // jauge de sprint : TROP TÔT / MAINTENANT / EN RETARD
  const rem=remainingM(progress[0]),reach=sprintReach(P,playerEnergy,cr),btn=$('#sprintBtn');
  if(!playerFinal){const k=reach/Math.max(1,rem);if(RS.idealAtM==null&&k>=.97)RS.idealAtM=rem;const st=phase<35?'wait':k<.9?'early':k<=1.12?'now':'late';if(btn.dataset.st!==st){btn.dataset.st=st;btn.innerHTML={wait:'SPRINT<small>plus tard</small>',early:'SPRINT<small>trop tôt</small>',now:'SPRINT<small>maintenant !</small>',late:'SPRINT<small>vite !</small>'}[st];if(st==='now'){buzz(15);coach.tip('sprint','Le bouton <b>SPRINT</b> devient vert : ton cheval a juste assez d’énergie pour sprinter jusqu’au poteau. C’est le moment idéal !','#sprintBtn')}}
   $('#sprintInfo').innerHTML=`Sprint possible : <b>${fmt(Math.round(Math.min(reach,9999)/10)*10)} m</b> · arrivée : <b>${fmt(Math.round(rem/10)*10)} m</b>`;const z=Math.max(0,Math.min(100,100-reach/RACE.dist*100));$('#mapIdeal').style.left=z+'%'}
  else $('#sprintInfo').innerHTML=playerEnergy>0?`Sprint final · <b>${fmt(Math.round(rem/10)*10)} m</b> à tenir`:'<b>Épuisé</b> : le cheval ralentit';
  $('#draft').classList.toggle('show',inDraft);$('#autoGallop').classList.toggle('blocked',boxed);$('#autoGallop b').textContent=boxed?'Foulée coupée':sprinting?'Sprint final':playerFinal?'Épuisé':inDraft?'À l’abri du vent':playerEnergy<20?'Endurance faible':'Foulée libre';
  if(boxed)$('#raceComment').textContent='Bloqué : décale-toi pour relancer';else if(inDraft)$('#raceComment').textContent='Dans le sillage : tu économises ton endurance';else if(sprinting)$('#raceComment').textContent=HN()+' accélère !';else if(turn>.35&&playerLane>35)$('#raceComment').textContent='Rapproche-toi de la corde';else if(phase>70&&!playerFinal)$('#raceComment').textContent='Surveille le bouton SPRINT : il passe au vert au bon moment';
  if(phase>75&&!runRaceV2.said){runRaceV2.said=1;sound.say('Dernière ligne droite !')}}
 for(let i=0;i<5;i++){const idx=i+1,ai=rivalAI[i];if(raceFinished[idx])continue;const own=progress[idx],lane=rivalLanes[i],near=nearbyHorses(idx),ahead=near.find(h=>Math.abs(h.l-lane)<12),ropeBusy=progress.some((p,j)=>j!==idx&&!raceFinished[j]&&Math.abs(p-own)<2.5&&(j? rivalLanes[j-1]:playerLane)<24),P=ai.P,early=own<55,MF=moments.fx(idx);
  if(raceTime>=ai.nextDecision){if(ahead&&ahead.gap<1.3&&ai.energy>23&&raceRng()<.68)ai.targetLane=clampRace(lane+(lane<70?17:-17),9,80);else if(ahead&&ahead.gap<4&&ai.energy<64)ai.targetLane=clampRace(ahead.l+raceRng()*5-2.5,9,80);else ai.targetLane=ropeBusy?28+raceRng()*9:10+raceRng()*9;ai.nextDecision=raceTime+10+Math.floor(raceRng()*20)}
  if(ahead&&ahead.gap<.85&&Math.abs(ai.targetLane-lane)<11)ai.targetLane=clampRace(lane+(lane<70?17:-17),9,85);const step=clampRace((ai.targetLane-lane)*.12,-.85,.85);rivalLanes[i]=clampRace(lane+step,8,90);
  const shelter=!!drafting(idx),curve=courseTurn(Math.min(1,own/100)),wide=curve*Math.max(0,rivalLanes[i]-19)/75,cr=P.cruise*(early?P.tactic.c:1)*(P.talent==='fusee'&&own<15?1.02:1)*(P.talent==='coeur'&&own>75&&progress.some((p,j)=>j!==idx&&p>own)?1.03:1);
  if(!ai.final&&own>40&&sprintReach(P,ai.energy,cr)>=remainingM(own)*(1+ai.err))ai.final=true;const attacking=ai.final&&ai.energy>0;
  ai.energy=clampRace(ai.energy-(attacking?P.sprintDrain*(shelter?.8:1):P.drain*(shelter?.5:1)*(early?P.tactic.d:1)*MF.drain)-wide*.03,0,100);
  const tired=ai.energy<=0?.84:ai.energy<15?.9:ai.energy<30?.96:1,target=(attacking?cr+P.sprint:own>72?cr+.045:cr)*(1-wide*.125)*tired+(shelter?P.draft:0)+MF.speed+(raceRng()-.5)*P.noise*6;ai.speed+=(target-ai.speed)*.16;progress[idx]+=ai.speed*raceScale}
 for(let i=0;i<6;i++)markFinish(i);const ranked=progress.map((p,i)=>({p,i})).sort((a,b)=>b.p-a.p),rank=raceFinished[0]?finishOrder.indexOf(0)+1:ranked.findIndex(x=>x.i===0)+1;$('#racePosition').textContent=rank+(rank===1?'er':'e');$('#meters').textContent=fmt(Math.max(0,Math.round(RACE.dist*(1-Math.min(100,progress[0])/100))));$('#mapDot').style.left=Math.min(100,progress[0])+'%';hooks.emit('race:tick');if(finishOrder.length===6)completeRace()}
function sprint(){if(playerFinal||!raceLoop||raceFinished[0]||playerEnergy<3)return;playerFinal=true;hooks.emit('race:sprint',remainingM(progress[0]),RS.idealAtM);RS.hadSprint=true;RS.sprintAtM=remainingM(progress[0]);buzz(25);sound.say('Il lance son sprint !');$('#sprintBtn').classList.add('active');$('#sprintBtn').disabled=true;$('#sprintBtn').innerHTML='SPRINT<small>en cours</small>';$('#mapIdeal').style.opacity=0}
/* analyse de course : 3 étoiles (départ, placement, sprint) + un conseil d'entraînement */
function raceAnalysis(rank){const RW=RS.window,r=RS.reaction,dep=r<RW*1.78,draftPct=RS.draft/Math.max(1,RS.ticks),railPct=RS.rail/Math.max(1,RS.ticks),boxPct=RS.boxed/Math.max(1,RS.ticks),place=(draftPct+railPct*.6)>=.45&&boxPct<.12;
 const ideal=RS.idealAtM,at=RS.sprintAtM,left=RS.sprintLeft,spr=RS.hadSprint&&RS.exhaustedM<40&&(left==null||left<22)&&(ideal==null||Math.abs(at-ideal)<ideal*.25+40);
 const lines=[[dep,'Départ',r?`Réaction ${Math.round(r)} ms${dep?'':' — trop lent'}`:'—'],[place,'Placement',`${Math.round(draftPct*100)} % dans un sillage · ${Math.round(railPct*100)} % à la corde${boxPct>.12?' · souvent enfermé':''}`],
  [spr,'Sprint final',!RS.hadSprint?'Jamais lancé !':RS.exhaustedM>=40?`Lancé trop tôt : épuisé sur ${Math.round(RS.exhaustedM)} m`:left!=null&&left>=22?`Lancé trop tard : ${Math.round(left)} % d’énergie inutilisée`:`Lancé à ${fmt(Math.round(at/10)*10)} m (idéal ≈ ${fmt(Math.round((ideal||at)/10)*10)} m)`]];
 const stars=lines.filter(l=>l[0]).length,h=stable.active();let adv=null;
 if(!dep)adv=['stalles','Travaille les sorties de stalles pour gagner en réactivité.'];else if(boxPct>.12)adv=['groupe','Ton cheval se fait enfermer : le galop en groupe améliore son intelligence de course.'];
 else if(RS.exhaustedM>=40||(RS.hadSprint&&h.stats.end<62))adv=['canter','Il manque d’endurance sur cette distance : fais-lui du canter long.'];else if(rank>1)adv=[h.stats.vit<=h.stats.acc?'galop':'fractionne',h.stats.vit<=h.stats.acc?'Il manque de vitesse de pointe : galop de vitesse à l’hippodrome.':'Son sprint manque de punch : fractionné à la carrière.'];
 return{lines,stars,adv}}
function completeRace(){clearInterval(raceLoop);raceLoop=null;
 // Défi du jour : ni trophées, ni gains, ni fatigue — le module 37-defi affiche son propre bilan
 if(RACE.defi){hooks.emit('defi:end');hooks.emit('race:end',finishOrder.indexOf(0)+1);return}
const rank=finishOrder.indexOf(0)+1,win=rank===1,A=raceAnalysis(rank);if(A.lines[2][0])career.bump('sprint');
 const CR=career.afterRace(rank,RACE,A.stars),prize=Math.round(purseOf(RACE)*[1,.46,.26,.17,.13,.1][rank-1]*(1+CR.streakBonus));state.gold+=prize;sync();const AR=stable.afterRace(stable.data.active,rank,6);
 sound.crowdLevel(1);setTimeout(()=>sound.crowdLevel(.2),2500);if(win){sound.fanfare();buzz([60,40,120])}else buzz(40);sound.say(`${raceNames[finishOrder[0]]} remporte le ${RACE.n} !`,true);
 $('#fbGain').innerHTML=`+${fmt(prize)} or${CR.streakBonus?` <small>(série ×${1+CR.streakBonus})</small>`:''}${dfx('hippodrome')>1&&prize?` <small>(hippodrome +${Math.round((dfx('hippodrome')-1)*100)} %)</small>`:''} · ${CR.d>0?'+':''}${CR.d} trophées · +${AR.xp} XP${AR.up?` · NIVEAU ${stable.active().level} !`:''}${CR.promoted?` · PROMU EN LIGUE ${CR.promoted.n.toUpperCase()} !`:CR.relegated?` · Retour en ligue ${CR.relegated.n}`:''}${CR.chest?`<br>🎁 Coffre ${CR.chest.n} gagné !`:CR.chestFull?'<br>🎁 Coffres pleins : ouvre-en un pour en gagner d’autres':''}`;
 $('#fbStars').innerHTML=`<div class="stars">${[0,1,2].map(i=>`<i class="${i<A.stars?'on':''}" style="animation-delay:${.3+i*.25}s">★</i>`).join('')}</div>${A.lines.map(([ok,n,t])=>`<div class="an ${ok?'ok':''}"><b>${ok?'✓':'✗'} ${n}</b><span>${t}</span></div>`).join('')}${A.adv?`<div class="an-adv">🎩 ${A.adv[1]} <button class="action" data-adv="${A.adv[0]}">ENTRAÎNER</button></div>`:''}`;
 {const rm=rival.after();$('#fbGain').innerHTML+=`<br>🎩 ${rm}`;const tm=tour.after(rank);if(tm)$('#fbGain').innerHTML+=`<br><span class="tourmsg">${tm}</span>`;tour.resultBtn();palmares.onRace(rank,A.stars)}currentField=null;const first=raceFinishTimes[finishOrder[0]];$('#finishRows').innerHTML=finishOrder.map((idx,pos)=>{const gap=raceFinishTimes[idx]-first;return `<tr class="${idx===0?'player':''}"><td>${pos+1}</td><td>${escapeHTML(raceNames[idx])}${idx===0?' • VOUS':''}</td><td>${raceFinishTimes[idx].toFixed(2)} s</td><td>${pos?`+${gap.toFixed(2)} s`:'—'}</td></tr>`}).join('');$('#raceComment').textContent='Classement officiel validé';$('#finishBoard').classList.add('show');$('#resultCup').textContent=win?'🏆':'🎖️';$('#resultTitle').textContent=win?'Victoire royale !':`${rank}e place`;$('#resultText').textContent=win?HN()+' monte sur la première marche du podium.':`${HN()} termine ${rank}e après une course disputée.`;hooks.emit('race:end',finishOrder.indexOf(0)+1)}
